apply plugin: 'java-library'

dependencies {
    // Selenium 
    api "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    api "io.github.bonigarcia:webdrivermanager:${webdrivermanager}"

    // OkHttp3 
    api "com.squareup.okhttp3:okhttp:${okHttpVersion}"
    api "com.squareup.okhttp3:logging-interceptor:${okHttpVersion}"

    // JUnit 5
    api "org.junit.jupiter:junit-jupiter-api:${junitVersion}"

    // Jackson for JSON parsing
    api "com.fasterxml.jackson.core:jackson-databind:2.18.2"
}
