# Browser configuration
browser=chrome
headless=false

# ChromeDriver configuration
chrome.for.testing=false
chrome.version=145
chrome.binary=/Applications/Chromium.app/Contents/MacOS/Chromium

# FirefoxDriver configuration
firefox.version=stable

# EdgeDriver configuration
edge.version=stable


# URL configuration
base.url=https://example.com
api.base.url=https://api.example.com

# Wait times
implicit.wait.seconds=10
explicit.wait.seconds=20
